### ISSUE TITLE
How do I pass through existing rich presence data

### ISSUE THREAD

**Issue by AstroFloof** [trickybestia/linux-discord-rich-presence#5]
I have my OS RP going, but I want other things such as my spotify showing as well. Is there a way to pass that in too?

**Comment by trickybestia** [comment]
@AstroFloof do you want to see two lines describing your current activity when you just click on your nickname, without opening your full profile? AFAIK, it is impossible.

**Comment by AstroFloof** [comment]
@trickybestia no, I mean when I'm listening to Spotify, there's a special rich presence Discord uses for that, which gets overridden by this. Is there a way to get that rich presence and tack it on to the payload the config gives?

**Comment by trickybestia** [comment]
@AstroFloof 
> Is there a way to get that rich presence and tack it on to the payload the config gives?

No, Spotify's rich presence differs from ones you can create on Discord Developer Portal.
By the way, there is a [feature request thread](https://support.discord.com/hc/en-us/community/posts/360045758192-Rich-Presence-Priorities) on discord forums which is same to your issue. You can upvote it.

So, this issue is more related to Discord, than linux-discord-rich-presence.
